import { Sen } from "next/font/google";
import "./globals.css";
import 'aos/dist/aos.css';

const sen = Sen({
  variable: "--font-sen",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sen.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
